// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr53XUimMlFEBEicbJ5v83y3kNQZTQchA',
    appId: '1:284298809502:web:2b932d1fad5423098eab8f',
    messagingSenderId: '284298809502',
    projectId: 'elratamapp-5e22b',
    authDomain: 'elratamapp-5e22b.firebaseapp.com',
    storageBucket: 'elratamapp-5e22b.firebasestorage.app',
    measurementId: 'G-F650HQJJQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB4pqnkp4cLOWhzckxImToxRdONoXXpIY',
    appId: '1:284298809502:android:3e9bf2b10bccdc4a8eab8f',
    messagingSenderId: '284298809502',
    projectId: 'elratamapp-5e22b',
    storageBucket: 'elratamapp-5e22b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzVWDCKlVM_PE0h3qbio-25kdOighzz0g',
    appId: '1:284298809502:ios:d4485b28cce3f21a8eab8f',
    messagingSenderId: '284298809502',
    projectId: 'elratamapp-5e22b',
    storageBucket: 'elratamapp-5e22b.firebasestorage.app',
    androidClientId: '284298809502-antmduqeis83koaif60qvmavli7g4840.apps.googleusercontent.com',
    iosClientId: '284298809502-kkfbrld5jeepobf4kd03ofd43c31q065.apps.googleusercontent.com',
    iosBundleId: 'com.example.elratamappNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzVWDCKlVM_PE0h3qbio-25kdOighzz0g',
    appId: '1:284298809502:ios:d4485b28cce3f21a8eab8f',
    messagingSenderId: '284298809502',
    projectId: 'elratamapp-5e22b',
    storageBucket: 'elratamapp-5e22b.firebasestorage.app',
    androidClientId: '284298809502-antmduqeis83koaif60qvmavli7g4840.apps.googleusercontent.com',
    iosClientId: '284298809502-kkfbrld5jeepobf4kd03ofd43c31q065.apps.googleusercontent.com',
    iosBundleId: 'com.example.elratamappNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr53XUimMlFEBEicbJ5v83y3kNQZTQchA',
    appId: '1:284298809502:web:e06b3e641aa314da8eab8f',
    messagingSenderId: '284298809502',
    projectId: 'elratamapp-5e22b',
    authDomain: 'elratamapp-5e22b.firebaseapp.com',
    storageBucket: 'elratamapp-5e22b.firebasestorage.app',
    measurementId: 'G-JQSH5QYLGE',
  );

}